### ISSUE TITLE
evaluate visual odometry

### ISSUE THREAD

**Issue by HuangGuoHui110** [alexklwong/unsupervised-depth-completion-visual-inertial-odometry#2]
Hi, there are only depth evaluation in this project, how do you evaluate your pose?

**Comment by alexklwong** [comment]
Hello, thank you for your interest, we measured the absolute trajectory error, relative pose error and relative rotation error
Their definitions were included in our supplementary materials.

As we progress with code cleanup/release, full implementation and examples will come as well. But in the short term (this week) I can include the implementations of the error metrics in src/eval_utils.py

**Comment by alexklwong** [comment]
Hello, you can use the pose evaluation metrics inside src/eval_utils.py, please see https://github.com/alexklwong/unsupervised-depth-completion-visual-inertial-odometry/commit/12d8beb280bbc5cea8512f2b9c74e21c4db930b0.
