### ISSUE TITLE
About FLOPS

### ISSUE THREAD

**Issue by Thermaloo** [alexklwong/unsupervised-depth-completion-visual-inertial-odometry#7]
Hello, Alex. Thank you for your excellent work. Could you tell me how much FLOPS is required?

**Comment by Thermaloo** [comment]
Hi, This is the evaluation result obtained by using the void_1500 pretrained model:
Evaluation results:
     MAE      RMSE      iMAE     iRMSE
  75.782   142.760    39.399    71.805
     +/-       +/-       +/-       +/-
  45.686    87.255    34.138    69.372
 Is it a reasonable result?

**Comment by alexklwong** [comment]
Hi,

Unfortunately, we don't have numbers for flops.

The evaluation results are correct.
